Change Group ID to "com.paiondata.elide"
paion-data/elide pull request #6
Opened 2024-04-03 08:38 UTC by Doom9527

Resolves #4

## Description
As a tech startup that evolves much quicker, we should fork Elide and quickly iterate it in our own organization at a much faster pace. To do that, we must [publish our own Elide fork to Maven central](https://github.com/orgs/paion-data/projects/10/views/1?pane=issue&itemId=57675835). The prerequisite of it, however, is to first change the [Group ID](https://maven.apache.org/guides/getting-started/#:~:text=groupId%20This%20element%20indicates%20the,maven.) of our fork, because without it we would not be able to publish our fork to Maven Central due to [namespace](https://central.sonatype.org/register/namespace/) collision

## Motivation and Context
I change all `com.yahoo.elide` to `com.paiondata.elide`.
I have used IntelliJ's automatic "refactor" feature to do batch renaming, but some types of files are manually renamed.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-04-04 14:30 UTC, Doom9527 commented
I forced the push after merging the several commit.

2024-04-08 11:09 UTC, QubitPi requested changes

2024-04-08 11:09 UTC, QubitPi commented on elide-async/pom.xml
> +        <version>1.0</version>
Maven release requires version to be `1.0-SNAPSHOT`

2024-04-10 11:01 UTC, QubitPi submitted a review, later dismissed

2024-04-17 02:14 UTC, closed without merging