Entity scan on non-existing data model package silences error
paion-data/elide pull request #8
Opened 2024-04-04 12:55 UTC by Doom9527

Resolves #1

## Description
This PR primarily addresses the scenario where `Elide` is configured with a non-existent data model package. With the updated implementation, `Elide` now fails to start gracefully and throws a runtime exception when encountering an invalid data model package during scanning.

## Motivation and Context
In the `Standalone` or other projects which import `Elide`, the `getAnnotatedClasses` of the `DefaultClassScanner` under the `Elide` is called to scan the package. I add a judgment on the Set, and throw an exception if it is empty.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-04-08 04:59 UTC, Doom9527 commented
The test class was able to run as expected, but I found that in the `import com.yahoo.elide.generated.parsers.ExpressionLexer;` will report an error, unable to find all directories under the `com.yahoo.elide.generated`. Then I added a dependency on the `elide-core 7.0.3` in the `pom.xml` to solve this problem. I am not sure if this is correct.

2024-04-08 04:59 UTC, Doom9527 commented
The test class was able to run as expected, but I found that in the `import com.yahoo.elide.generated.parsers.ExpressionLexer;` will report an error, unable to find all directories under the `com.yahoo.elide.generated`. Then I added a dependency on the `elide-core 7.0.3` in the `pom.xml` to solve this problem. I am not sure if this is correct.

2024-04-08 06:10 UTC, QubitPi requested changes

2024-04-08 06:10 UTC, QubitPi commented on elide-core/pom.xml
> +        </dependency>
Why would elide-core import itself？ <img width="50px" src="https://github.com/paion-data/elide/assets/16126939/d4851ea5-f1b9-4fb2-a67e-317e9dd60031"/>

2024-04-08 06:10 UTC, QubitPi commented on elide-core/src/test/java/com/yahoo/elide/core/utils/ClassScannerTest.java
> +    public void testGetAnnotatedClasses_NoClassesFound() {
Java goes with [camel case instead of underscore](https://en.wikipedia.org/wiki/Naming_convention_(programming)), it is better with 

```java
testGetAnnotatedClassesNoClassesFound
```

2024-04-08 06:10 UTC, QubitPi commented on elide-core/src/test/java/com/yahoo/elide/core/utils/ClassScannerTest.java
> +        assertEquals(33, classes.size(), "Actual: " + classes);
What does 33 signify? It is makes the code much less readable.

Industrial software engineering is all about two things:

1. Code **readability** ("Can other team member understand what your code is doing?")
2. Code **maintainability** ("Can other team member easily make modifications to the code base regardless of the size of the code base")

2024-04-08 07:23 UTC, Doom9527 commented on elide-core/pom.xml
> +        </dependency>
I look at `7.0.2` of the `elide-core` that I imported and found that the old` 7.0.2` version had the folder `generate`, the project couldn't start without it.
![1712560968600](https://github.com/paion-data/elide/assets/164460473/18069a82-b28b-4b33-a96f-2a169d038899)
![1712560984600](https://github.com/paion-data/elide/assets/164460473/5443d511-579c-4d17-af35-86e0ff2031a7)

2024-04-21 22:49 UTC, QubitPi approved these changes

2024-04-21 22:49 UTC, merged